name: CI/CD Pipeline

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  build:
    # Define the runner environment for the job
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node.js version 20
          node-version: '20'

      # Set execute permissions for script files
      - name: Set execute permissions
        run: |
          chmod +x scripts/build-angular.sh
          chmod +x scripts/deploy.sh

      # Build the Angular application
      - name: Build Angular app
        run: ./scripts/build-angular.sh

      # Upload the build artifacts (e.g., Angular dist files) for further use or archiving
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/lazy-pro

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permissions
        run: chmod +x scripts/deploy.sh

      - name: Deploy to Hostinger
        run: ./scripts/deploy.sh ${{ secrets.HOSTINGER_HOST }} ${{ secrets.HOSTINGER_USER }} ${{ secrets.HOSTINGER_SSH_KEY }}
